//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppForAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Computer
    {
        public string CID { get; set; }
        public string Brand { get; set; }
        public string Proccessor { get; set; }
        public string Ram { get; set; }
        public string HID { get; set; }
        public string LID { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Lab Lab { get; set; }
        public virtual Software Software { get; set; }
    }
}
