//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppForAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Degree
    {
        public Degree()
        {
            this.Students = new HashSet<Student>();
        }
    
        public string DID { get; set; }
        public string Name { get; set; }
        public string University { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Student> Students { get; set; }
    }
}
