//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppForAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lecturer_Hall
    {
        public string Username { get; set; }
        public string HID { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Hall Hall { get; set; }
        public virtual Lecturer Lecturer { get; set; }
    }
}
