//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppForAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Software
    {
        public Software()
        {
            this.Computers = new HashSet<Computer>();
        }
    
        public string SID { get; set; }
        public string Name { get; set; }
        public string Key_ { get; set; }
    
        public virtual ICollection<Computer> Computers { get; set; }
    }
}
