//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAppForAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Labs = new HashSet<Lab>();
        }
    
        public string Username { get; set; }
        public string S_ID { get; set; }
        public string DID { get; set; }
        public string BID { get; set; }
    
        public virtual Batch Batch { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Lab> Labs { get; set; }
    }
}
